import {
  ChannelType,
  EmbedBuilder,
  Events,
  Guild,
  PermissionFlagsBits,
  type Client,
  type TextChannel
} from "discord.js";
import { logger } from "../logger.js";
import { embedColor } from "../config.js";
import { emojis } from "../ui/emojis.js";
import type { DmDeliveryStatus } from "./moderation-notifications.js";

const channelName = "xavion-modlogs";
const pendingChannels = new Map<string, Promise<TextChannel | null>>();

export interface ModerationLog {
  action: string;
  moderatorId: string;
  target?: string;
  reason?: string;
  details?: string;
  dmStatus?: DmDeliveryStatus;
}

export function registerModLogSetup(client: Client): void {
  client.on(Events.GuildCreate, (guild) => void ensureModLogChannel(guild));
}

export async function ensureAllModLogChannels(client: Client): Promise<void> {
  await Promise.allSettled(client.guilds.cache.map((guild) => ensureModLogChannel(guild)));
}

export async function ensureModLogChannel(guild: Guild): Promise<TextChannel | null> {
  const existing = guild.channels.cache.find(
    (channel): channel is TextChannel =>
      channel.type === ChannelType.GuildText && channel.name === channelName
  );
  if (existing) return existing;

  const pending = pendingChannels.get(guild.id);
  if (pending) return pending;

  const creation = createModLogChannel(guild).finally(() => pendingChannels.delete(guild.id));
  pendingChannels.set(guild.id, creation);
  return creation;
}

async function createModLogChannel(guild: Guild): Promise<TextChannel | null> {
  const me = guild.members.me;
  if (!me?.permissions.has(PermissionFlagsBits.ManageChannels)) {
    logger.warn({ guildId: guild.id }, "Cannot create xavion-modlogs without Manage Channels");
    return null;
  }

  try {
    return await guild.channels.create({
      name: channelName,
      type: ChannelType.GuildText,
      topic: "Automatic moderation logs generated by Xavion",
      reason: "Xavion moderation logging setup",
      permissionOverwrites: [
        {
          id: guild.roles.everyone.id,
          deny: [PermissionFlagsBits.ViewChannel]
        },
        {
          id: me.id,
          allow: [
            PermissionFlagsBits.ViewChannel,
            PermissionFlagsBits.SendMessages,
            PermissionFlagsBits.EmbedLinks,
            PermissionFlagsBits.ReadMessageHistory
          ]
        }
      ]
    });
  } catch (error) {
    logger.error({ error, guildId: guild.id }, "Failed to create xavion-modlogs");
    return null;
  }
}

export async function sendModerationLog(
  guild: Guild,
  entry: ModerationLog
): Promise<void> {
  const channel = await ensureModLogChannel(guild);
  if (!channel) return;

  const embed = new EmbedBuilder()
    .setColor(embedColor)
    .setTitle(`<:Xavion_info:1514856459765022750> Moderation: ${entry.action}`)
    .addFields(
      { name: "Moderator", value: `<@${entry.moderatorId}>`, inline: true },
      { name: "Target", value: entry.target ?? "N/A", inline: true },
      {
        name: "DM Status",
        value: formatDmStatus(entry.dmStatus ?? "not_applicable"),
        inline: true
      },
      { name: "Reason", value: entry.reason ?? "No reason provided" }
    )
    .setFooter({ text: `Guild ID: ${guild.id}` });

  if (entry.details) embed.addFields({ name: "Details", value: entry.details });
  await channel.send({
    embeds: [embed],
    allowedMentions: { parse: [] }
  }).catch((error) => {
    logger.error({ error, guildId: guild.id }, "Failed to send moderation log");
  });
}

function formatDmStatus(status: DmDeliveryStatus): string {
  if (status === "delivered") return `${emojis.success} Delivered`;
  if (status === "failed") return `${emojis.error} Failed`;
  return `${emojis.info} Not applicable`;
}
